db:
  url: "sqlite:///./db/msalde.db"
sub_runs:
  config_file: "./config/simulations.yaml"
external_repo:
  clinvar_dir: ~/gitrepo/msalde/data/clinvar
datasets:
  brenan:
    data_loader_type: file_loader
    input_path: "../EvolvePro/output/dms/brenan_labels.csv"
    wild_type_id: "WT"
    column_names:
      id_col: "variant"
      # sequence_col: "variant"
      score_col1: "activity_scaled"
      score_col: "activity"
    embeddings_file: "../EvolvePro/output/plm/esm/brenan_esm2_t6_8M_UR50D.csv"
    fasta_file: "../EvolvePro/output/dms/brenan.fasta"
  cas12f:
    data_loader_type: file_loader
    input_path: "../EvolvePro/output/dms/cas12f_labels.csv"
    wild_type_id: "WT"
    column_names:
      id_col: "variant"
      sequence_col: "variant"
      score_col1: "activity_scaled"
      score_col: "activity"
    embeddings_file: "../EvolvePro/output/plm/esm/cas12f_esm2_t6_8M_UR50D.csv"
  cas12f1:
    data_loader_type: file_loader
    input_path: "../EvolvePro/output/dms/cas12f1_labels.csv"
    wild_type_id: "WT"
    column_names:
      id_col: "variant"
      # sequence_col: "sequence"
      score_col1: "activity_scaled"
      score_col: "activity"
    embeddings_file: "../EvolvePro/output/plm/esm/cas12f_esm2_t6_8M_UR50D.csv"
    fasta_file: "../EvolvePro/output/dms/cas12f.fasta"
  cas12f2:
    data_loader_type: file_loader
    input_path: "../EvolvePro/output/dms/cas12f2_labels.csv"
    wild_type_id: "WT"
    column_names:
      id_col: "variant"
      # sequence_col: "sequence"
      score_col1: "activity_scaled"
      score_col: "activity"
    embeddings_file: "../EvolvePro/output/plm/esm/cas12f_esm2_t6_8M_UR50D.csv"
    fasta_file: "../EvolvePro/output/dms/cas12f.fasta"
  ADRB2:
    data_loader_type: file_loader
    input_path: /home/claudiof/ADRB2_labels.csv
    wild_type_id: "WT"
    column_names:
      id_col: "mutant"
      # sequence_col: "sequence"
      score_col: "DMS_score"
    embeddings_file: /home/claudiof/ADRB2_esm2_t33_650M_UR50D.csv
    fasta_file: /home/claudiof/ADRB2.fasta
general:
  store_acquired_variants: true
c1:
  default_dataset: cas12f
  data_loader:
    type: file_loader
    dataset_name: "cas12f"
    # input_path: "../EvolvePro/output/dms/brenan_labels.csv"
    # input_path: "../EvolvePro/output/dms/cas12f1_labels.csv"
    input_path: "../EvolvePro/output/dms/cas12f_labels.csv"
    wild_type_id: "WT"
    column_names:
      id_col: "variant"
      # name_col: "variant"
      sequence_col: "variant"
      score_col1: "activity_scaled"
      score_col: "activity"
  data_loader1:
    input_path: "../EvolvePro/output/dms/brenan1_labels.csv"
    # input_path: "./test_data/test_assay_small1.csv"
    column_names:
      id_col: "id"
      # name_col: "id"
      sequence_col: "sequence"
      score_col: "score"
    sequence_generator:
      name: single_aa_substitution
      wt_fasta_file: "./test_data/test_assay_small1.fasta"
      substitution_col: "variant"
  embedder:
    type: file_loader
    model_name: facebook/esm2_t2_8M_UR50D
    # embeddings_file: ../EvolvePro/output/plm/esm/brenan1_esm2_t6_8M_UR50D.csv
    embeddings_file: ../EvolvePro/output/plm/esm/cas12f_esm2_t6_8M_UR50D.csv
  embedder1:
    type: esm
    model_name1: esm2_t2_8M_UR50D
    model_name: facebook/esm2_t33_650M_UR50D
    parameters:
      cache_dir: "./model_cache"
      device: "cpu"
      batch_size: 8
      use_pooling: true
      quantize: false
  simulation_config_id: c9
c2:
  default_dataset: cas12f
  embedder:
    type: file_loader
    model_name: esm2_t2_8M_UR50D
    # embeddings_file: ../EvolvePro/output/plm/esm/brenan1_esm2_t6_8M_UR50D.csv
    # embeddings_file: ../EvolvePro/output/plm/esm/cas12f_esm2_t6_8M_UR50D.csv
  simulation_config_id: c9
c2_1:
  default_dataset: cas12f
  embedder:
    type: file_loader
    model_name: esm2_t6_8M_UR50D
    # embeddings_file: ../EvolvePro/output/plm/esm/brenan1_esm2_t6_8M_UR50D.csv
    # embeddings_file: ../EvolvePro/output/plm/esm/cas12f_esm2_t6_8M_UR50D.csv
  simulation_config_id: c9_2
c3:
  data_loader:
    type: file_loader
    dataset_name: "cas12f"
    # input_path: "../EvolvePro/output/dms/brenan_labels.csv"
    # input_path: "../EvolvePro/output/dms/cas12f1_labels.csv"
    input_path: "../EvolvePro/output/dms/cas12f_labels.csv"
    wild_type_id: "WT"
    column_names:
      id_col: "variant"
      # name_col: "variant"
      sequence_col: "variant"
      score_col1: "activity_scaled"
      score_col: "activity"
  embedder:
    type: file_loader
    model_name: esm2_t2_8M_UR50D
    # embeddings_file: ../EvolvePro/output/plm/esm/brenan1_esm2_t6_8M_UR50D.csv
    embeddings_file: ../EvolvePro/output/plm/esm/cas12f_esm2_t6_8M_UR50D.csv
c3_1:
  default_dataset: cas12f
  simulation_config_id: c3_1
  embedder:
    type: file_loader
    model_name: esm2_t6_8M_UR50D
c3_2:
  default_dataset: cas12f
  simulation_config_id: c3_2
  embedder:
    type: file_loader
    model_name: esm2_t6_8M_UR50D
c3_3:
  default_dataset: cas12f
  simulation_config_id: c3_3
  embedder:
    type: file_loader
    model_name: esm2_t6_8M_UR50D
c9_1:
  default_dataset: cas12f
  simulation_config_id: c9_1
c9_2:
  default_dataset: cas12f
  simulation_config_id: c9_2
c9_3:
  default_dataset: cas12f
  simulation_config_id: c9_3
c10:
  default_dataset: cas12f
  simulation_config_id: c10
  log_likelihood_ratio_computer:
    type: ESM2LLRComputer
    parameters:
      base_model_name: facebook/esm2_t6_8M_UR50D
      batch_size: 32
